// /src/types/events.ts
export const CLIENT_EVENTS = {
    SEND_MESSAGE: 'SEND_MESSAGE',
    EDIT_MESSAGE: 'EDIT_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ADD_REACTION: 'ADD_REACTION',
    REMOVE_REACTION: 'REMOVE_REACTION',
    START_TYPING: 'START_TYPING',
    STOP_TYPING: 'STOP_TYPING',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    FETCH_CHANNELS: 'FETCH_CHANNELS',
    JOIN_CHANNEL: 'JOIN_CHANNEL',
    LEAVE_CHANNEL: 'LEAVE_CHANNEL',
    UPLOAD_MEDIA: 'UPLOAD_MEDIA',
    MARK_AS_READ: 'MARK_AS_READ',
    PING: 'PING',
  // Social features
  FOLLOW_USER: 'FOLLOW_USER',
  UNFOLLOW_USER: 'UNFOLLOW_USER',
  SEND_POKE: 'SEND_POKE',
  GET_USER_STATUS: 'GET_USER_STATUS',
  CHECK_FOLLOW_STATUS: 'CHECK_FOLLOW_STATUS',
  GET_USER_STATS: 'GET_USER_STATS',
  // Room features
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  GET_ROOM_INFO: 'GET_ROOM_INFO',
  CREATE_ROOM_INVITE: 'CREATE_ROOM_INVITE',
  USE_ROOM_INVITE: 'USE_ROOM_INVITE',
  GET_USER_ROOMS: 'GET_USER_ROOMS',
  SEARCH_ROOMS: 'SEARCH_ROOMS',
  // DM features
  CREATE_DM: 'CREATE_DM'
  } as const;
  
  export const SERVER_EVENTS = {
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGE_EDITED: 'MESSAGE_EDITED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',
    REACTION_ADDED: 'REACTION_ADDED',
    REACTION_REMOVED: 'REACTION_REMOVED',
    TYPING_STARTED: 'TYPING_STARTED',
    TYPING_STOPPED: 'TYPING_STOPPED',
    USER_JOINED: 'USER_JOINED',
    USER_LEFT: 'USER_LEFT',
    USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
    READ_RECEIPT_UPDATED: 'READ_RECEIPT_UPDATED',
    MEDIA_UPLOADED: 'MEDIA_UPLOADED',
    MESSAGES_LOADED: 'MESSAGES_LOADED',
    CHANNELS_LOADED: 'CHANNELS_LOADED',
    CHANNEL_CREATED: 'CHANNEL_CREATED',
    NEW_DM_INVITE: 'NEW_DM_INVITE',
    PONG: 'PONG',
    ERROR: 'ERROR',
    CONNECTION: 'CONNECTION',
  // Social features
  FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
  UNFOLLOW_SUCCESS: 'UNFOLLOW_SUCCESS',
  POKE_SENT: 'POKE_SENT',
  POKE_RECEIVED: 'POKE_RECEIVED',
  USER_STATUS_RESPONSE: 'USER_STATUS_RESPONSE',
  NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',
  FOLLOW_STATUS_RESPONSE: 'FOLLOW_STATUS_RESPONSE',
  USER_STATS_RESPONSE: 'USER_STATS_RESPONSE',
  // Room features
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_LEFT: 'ROOM_LEFT',
  ROOM_INFO_RESPONSE: 'ROOM_INFO_RESPONSE',
  ROOM_INVITE_CREATED: 'ROOM_INVITE_CREATED',
  ROOM_INVITE_USED: 'ROOM_INVITE_USED',
  USER_ROOMS_RESPONSE: 'USER_ROOMS_RESPONSE',
  ROOMS_SEARCH_RESPONSE: 'ROOMS_SEARCH_RESPONSE',
  ROOM_ERROR: 'ROOM_ERROR',
  // DM features
  DM_CREATED: 'DM_CREATED',
  // Storage features
  STORAGE_RESPONSE: 'STORAGE_RESPONSE'
} as const;
  
  export type ClientEvent = keyof typeof CLIENT_EVENTS;
  export type ServerEvent = keyof typeof SERVER_EVENTS;